name: Deploy Eventually (In)Consistent

on:
  push:
    branches:
      - main  # Trigger on pushes to the main branch

jobs:
    build-and-deploy:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v4
              with:
                fetch-depth: 0
                submodules: true

            - name: Setup Hugo
              uses: peaceiris/actions-hugo@v3
              with: 
                    hugo-version: 'latest'
                    extended: true
            
            - name: Build blog
              run: hugo --minify

            - name: Deploy to Server
              uses: appleboy/scp-action@master
              with:
                host: ${{ secrets.TECHBLOG_HOST }}
                username: ${{ secrets.TECHBLOG_USER }}
                key: ${{ secrets.TECHBLOG_KEY }}
                source: "public/"
                target: "/cotti.com.br/tech/"